services:
  healthatlas-core:
    build:
      context: .
      dockerfile: Dockerfile.jvm
      args:
        - APP_DIR=build/quarkus-app
    image: healthatlas-core:latest
    container_name: athena
    ports:
      - "8080:8080"                 # host:container (so host 8080 -> container 8080)
    networks:
      - healthatlas
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://athena-db:5432/healthatlas
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_PROFILE: docker
    depends_on:
      athena-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/q/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  athena-db:
    image: postgres:15
    container_name: athena-db
    environment:
      POSTGRES_DB: healthatlas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"   # expose DB port to host (5433)
    networks:
      - healthatlas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
    volumes:
      - pgdata-athena:/var/lib/postgresql/data

networks:
  healthatlas:
    external: true

volumes:
  pgdata-athena:
